name: Actualizador de Parleys

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de actualización
        env:
          SPORTS_API_KEY: ${{ secrets.SPORTS_API_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDS_PATH: ${{ secrets.GOOGLE_CREDS_PATH }}

        run: python main.py
